---
- name: creating user
  hosts: all
  gather_facts: no
  become: true
  vars:
     user_name: sruthi
  tasks:
   - name: creating user {{ user_name }}
     user: 
      name: "{{ user_name }}"
   - name: create a directory
     file:
      path: /opt/{{ user_name}}__temp_dir 
      state: directory
      owner: "{{ user_name }}"
      group: "{{user_name}}"    
      mode: 0755
