---
- name: Removing multiple packages
  hosts: all
  become: true
  gather_facts: yes
  tasks:
   - name: Remove packages
     yum:
      name: "{{ item }}"
      state: removed
     with_items:
      - git
      - wget
      - make
      - telnet
      - gzip


