---
- name: playbook to install apache tomcat
  hosts: webservers
  become: true
  gather_facts: yes
  #vars:
  #tomcat_url: https://ftp.wayne.edu/apache/tomcat/tomcat-8/v8.5.61/bin/apache-tomcat-8.5.61.tar.gz
  #tomcat_package: apache-tomcat-8.5.61
  vars_files:
   - tomcat_vars.yml
  
  
  tasks:
   - name: install java-1.8*
     yum:
       name: java
       state: installed         
   - name: downloading tomcat packages         
     get_url:
       url: "{{ tomcat_url }}"     
             #url: https://ftp.wayne.edu/apache/tomcat/tomcat-8/v8.5.61/bin/apache-tomcat-8.5.61.tar.gz
       dest: /opt
       mode: 0755
      

   - name: extract packages
     unarchive:
      #src: /opt/apache-tomcat-8.5.61.tar.gz
       src: /opt/{{ tomcat_package }}.tar.gz
       dest: /opt
       remote_src: yes
   - name: change permissions on apache-tomcat file
     file:
             #path: /opt/apache-tomcat-8.5.61
       path: /opt/{{ tomcat_package }}
       mode: 0755
       recurse: yes

   - name: creating link file
     file:
             # src: /opt/apache-tomcat-8.5.61/bin/startup.sh

       src: /opt/{{ tomcat_package }}/bin/startup.sh

       dest: /usr/local/bin/tomcatup
       state: link
   - name: creating link file for tomcat shutdown
     file:
       #src: /opt/apache-tomcat-8.5.61/bin/shutdown.sh
       src: /opt/{{ tomcat_package }}/bin/shutdown.sh
       dest: /usr/local/bin/tomcatdown
       state: link
   - name: start the services
     command: nohup ./startup.sh
     args:
       chdir: /opt/{{ tomcat_package }}/bin
       #chdir: /opt/apache-tomcat-8.5.61/bin
   
