---
- name: playbook to install apache tomcat
  hosts: webservers
  become: true
  gather_facts: yes
  tasks:
   - name: install java-1.8*
     yum:
       name: java
       state: installed         
   - name: downloading tomcat packages         
     get_url:
         
       url: https://ftp.wayne.edu/apache/tomcat/tomcat-8/v8.5.61/bin/apache-tomcat-8.5.61.tar.gz
       dest: /opt
       mode: 0755
      

   - name: extract packages
     unarchive:
       src: /opt/apache-tomcat-8.5.61.tar.gz
       dest: /opt
       remote_src: yes
   - name: change permissions on apache-tomcat file
     file:
       path: /opt/apache-tomcat-8.5.61
       mode: 0755
       recurse: yes

   - name: creating link file
     file:
       src: /opt/apache-tomcat-8.5.61/bin/startup.sh
       dest: /usr/local/bin/tomcatup
       state: link
   - name: creating link file for tomcat shutdown
     file:
       src: /opt/apache-tomcat-8.5.61/bin/shutdown.sh
       dest: /usr/local/bin/tomcatdown
       state: link
   - name: start the services
     command: nohup ./startup.sh
     args:
       
       chdir: /opt/apache-tomcat-8.5.61/bin
   
